I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 19, in script
    scene hero_monit with dissolve_time
  File "game/script.rpy", line 19, in <module>
    scene hero_monit with dissolve_time
NameError: name 'dissolve_time' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 19, in script
    scene hero_monit with dissolve_time
  File "C:\Dev\renpy-8.1.3-sdk\renpy\ast.py", line 1674, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Dev\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Dev\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 19, in <module>
    scene hero_monit with dissolve_time
NameError: name 'dissolve_time' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Alert 1.0
Mon Nov 13 21:18:12 2023
